apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-api-testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prime-api-testing

  template:
    metadata:
      labels:
        app: prime-api-testing

    spec:
      containers:
        - name: prime-api-testing
          image: kupr744/prime-api-testing
          imagePullPolicy: Always
          ports:
            - containerPort: 3001