apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress-v2
  namespace: canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "30"
  labels:
    name: myingress-v2
spec:
  rules:
    - http:
        paths:
        - pathType: Prefix
          path: "/prime"
          backend:
            service:
              name: prime-api-service-v2
              port:
                number: 80
  ingressClassName: nginx