apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      #version: v2

  template:
    metadata:
      labels:
        app: backend
        #version: v2

    spec:
      containers:
        - name: backend
          image: kupr744/backend
          env:
          - name: NODE_ENV
            value: "development"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-api-testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prime-api-testing

  template:
    metadata:
      labels:
        app: prime-api-testing

    spec:
      containers:
        - name: prime-api-testing
          image: kupr744/prime-api-testing
          env:
          - name: NODE_ENV
            value: "development"
          imagePullPolicy: Always
          ports:
            - containerPort: 3001