apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-v2
  namespace: canary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-canary

  template:
    metadata:
      labels:
        app: backend-canary

    spec:
      containers:
        - name: backend
          image: kupr744/backend
          env:
          - name: NODE_ENV
            value: "development"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-api-v2
  namespace: canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prime-api-canary

  template:
    metadata:
      labels:
        app: prime-api-canary

    spec:
      containers:
        - name: prime-api-v2
          image: kupr744/prime-api:testing
          env:
          - name: NODE_ENV
            value: "development"
          imagePullPolicy: Always
          ports:
            - containerPort: 3001