apiVersion: apps/v1
kind: Deployment
metadata:
  name: primeservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: primeservice

  template:
    metadata:
      labels:
        app: primeservice

    spec:
      containers:
        - name: primeservice
          image: primeservice
          env:
          - name: NODE_ENV
            value: "development"
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          
