apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prime-api

  template:
    metadata:
      labels:
        app: prime-api

    spec:
      containers:
        - name: prime-api
          image: kupr744/prime-api
          env:
          - name: NODE_ENV
            value: "development"
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          
