apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prime-api

  template:
    metadata:
      labels:
        app: prime-api

    spec:
      containers:
        - name: prime-api
          image: prime-api
          env:
          - name: NODE_ENV
            value: "development"
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          
