apiVersion: apps/v1
kind: Deployment
metadata:
  name: appserver-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appserver

  template:
    metadata:
      labels:
        app: appserver

    spec:
      containers:
        - name: appserver
          image: username/appname #TODO DockerHub Containername
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          
