apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: kupr744/backend
          env:
          - name: NODE_ENV
            value: "development"
          imagePullPolicy: Never
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
