apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: kupr744/backend
          env:
          - name: NODE_ENV
            value: "development"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
