apiVersion: v1
kind: Service
metadata:  
  name: backend-nodeport-service
spec:
  type: NodePort
  selector:    
    app: backend
  ports:  
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30005
    protocol: TCP