name: ab-testing

on:
  push:
    branches:
      - "ab-testing"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:web_application/prime-api"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/prime-api-testing


  deploy-2-gcloud:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: authenticate
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    
    - name: connect to gke
      run: |-
        gcloud ${{ secrets.GKE }}

    - name: rollout
      run: |-
        kubectl apply -f canary_ingress.yaml
        kubectl apply -f canary_service.yaml
        kubectl apply -f canary_deployment.yaml
        
    