name: deploy k8s cluster 2 gcloud

on:
  push: 
    tags:
      - 'v*.*.*'

jobs:
  deploy-2-gcloud:
    needs: [deploy-backend-docker, deploy-prime-docker]
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: authenticate
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    
    - name: connect to gke
      run: |-
        gcloud ${{ secrets.GKE }}

    - name: rollout
      run: |-
        kubectl set image deployment/prime-api prime-api=kupr744/prime-api:${{github.ref_name}}

    - name: remove canary files
      run: |- 
        kubectl delete ing myingress-v2
        kubectl delete svc prime-api-service-v2
        kubectl delete pod -l app=prime-api-testing
