name: deploy k8s cluster 2 gcloud

on:
  push: 
    tags:
      - 'v*.*.*'

jobs:
  deploy-prime-docker:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/prime-api
          tags: |
            type=semver,pattern={{raw}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:web_application/prime-api"
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy-2-gcloud:
    needs: [deploy-prime-docker]
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: authenticate
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    
    - name: connect to gke
      run: |-
        gcloud ${{ secrets.GKE }}

    - name: rollout
      run: |-
        kubectl set image deployment/prime-api prime-api=kupr744/prime-api:${{github.ref_name}}

    - name: remove canary files
      run: |- 
        kubectl delete ing myingress-v2
        kubectl delete svc prime-api-service-v2
        kubectl delete pod -l app=prime-api-testing
