name: deploy k8s cluster 2 gcloud

on:
  workflow_run:
    workflows: ["µService deploy 2 docker"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: authenticate
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    
    - name: rollout
      run: kubectl set image deployment/prime-api prime-api=kupr744/prime-api:${{github.ref_name}}

    - name: remove canary files
      run: kubectl delete all --all -n canary
